import { saveAs } from 'file-saver';
import Image from 'next/image';
import { toast } from 'react-hot-toast';

const ImageResponse = ({ interact }) => {
  const copyText = () => {
    navigator.clipboard
      .writeText(interact.prompt)
      .then(() => toast.success('کپی شد', { className: 'font-yekan' }))
      .catch(() => toast.error('مشکلی پیش آمده', { className: 'font-yekan' }));
  };
  if (interact) {
    return (
      <article
        className={` bg-opacity-80 w-[85%] rounded-xl p-4 mt-4 animate-appear ${
          interact.url
            ? 'bg-primary text-neutral-50 self-end'
            : 'bg-neutral-300 dark:bg-neutral-600 text-neutral-900 dark:text-neutral-50'
        }`}
        dir={
          interact.prompt && /[\u0591-\u07FF]/.test(interact.prompt)
            ? 'rtl'
            : 'ltr'
        }
      >
        {interact?.status === 'error' ? (
          <div className="flex">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              className="w-6 h-6 text-rose-700"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
              />
            </svg>
            <h4 className="mb-1 font-extrabold leading-8 text-lg select-none">
              {interact.prompt ? 'YOU' : 'DALL·E'}
            </h4>
          </div>
        ) : (
          <h4 className="mb-1 font-extrabold leading-8 text-lg select-none">
            {interact.prompt ? 'YOU' : 'DALL·E'}
          </h4>
        )}

        {!!interact.prompt && (
          <>
            <p>{interact.prompt}</p>
            {navigator.clipboard && navigator.clipboard.writeText ? (
              <button onClick={copyText} className="mt-4">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M8.25 7.5V6.108c0-1.135.845-2.098 1.976-2.192.373-.03.748-.057 1.123-.08M15.75 18H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08M15.75 18.75v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5a1.125 1.125 0 01-1.125-1.125v-1.5A3.375 3.375 0 006.375 7.5H5.25m11.9-3.664A2.251 2.251 0 0015 2.25h-1.5a2.251 2.251 0 00-2.15 1.586m5.8 0c.065.21.1.433.1.664v.75h-6V4.5c0-.231.035-.454.1-.664M6.75 7.5H4.875c-.621 0-1.125.504-1.125 1.125v12c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V16.5a9 9 0 00-9-9z"
                  />
                </svg>
              </button>
            ) : (
              ''
            )}
          </>
        )}
        {!!interact.url && (
          <>
            <Image
              blurDataURL="/images/loading-blur.jpg"
              placeholder="blur"
              width={128}
              height={128}
              className="w-full h-auto rounded-xl"
              src={interact.url}
              priority
              alt="ai generated image"
            />
            <div className="mt-4 flex justify-between items-end">
              <button onClick={() => saveAs(interact.url, 'Ai-generated.png')}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-7 h-7 "
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M9 13.5l3 3m0 0l3-3m-3 3v-6m1.06-4.19l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z"
                  />
                </svg>
              </button>
              <span className="font-colfax font-thin text-xs text-neutral-300 select-none text-end">
                Generated by DALL.E powered by OpenAI
              </span>
            </div>
          </>
        )}
      </article>
    );
  }
  return <></>;
};

export default ImageResponse;
