import { saveAs } from 'file-saver';
import Image from 'next/image';

const ImageResponse = ({ interact }) => {
  if (interact) {
    return (
      <article
        className={` bg-opacity-80 w-[85%] rounded-xl p-4 mt-4 animate-appear ${
          interact.url
            ? 'bg-primary text-neutral-50 self-end'
            : 'bg-neutral-300 dark:bg-neutral-600 text-neutral-900 dark:text-neutral-50'
        }`}
        dir={
          interact.prompt && /[\u0591-\u07FF]/.test(interact.prompt)
            ? 'rtl'
            : 'ltr'
        }
      >
        <h4 className="mb-1 font-extrabold leading-8 text-lg select-none">
          {interact.prompt ? 'YOU' : 'DALL·E'}
        </h4>
        {interact.prompt && <p>{interact.prompt}</p>}
        {interact.url && (
          <>
            <Image
              blurDataURL="/images/loading-blur.jpg"
              placeholder="blur"
              width={512}
              height={512}
              className="w-full h-auto rounded-xl"
              src={interact.url}
              alt="ai generated image"
            />
            <div className="mt-4 flex justify-between items-end">
              <button onClick={() => saveAs(interact.url, 'Ai-generated.png')}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-7 h-7 "
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M9 13.5l3 3m0 0l3-3m-3 3v-6m1.06-4.19l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z"
                  />
                </svg>
              </button>
              <span className="font-colfax font-thin text-xs text-neutral-300 select-none">
                Generated by DALL.E powered by OpenAI
              </span>
            </div>
          </>
        )}
      </article>
    );
  }
  return <></>;
};

export default ImageResponse;
